services:
  app:
    container_name: pizzastore
    build:
      context: .
      dockerfile: PizzaStore/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
